### PR TITLE
Set_up #1

### PR DESCRIPTION
**Pull request by Luis93Hub**

### CODE REVIEW

**Review by edysmp — CHANGES_REQUESTED** [review]
Getting this when trying to install site.
```ddev drush si --existing-config

 You are about to:
 * DROP all tables in your 'db' database.

 Do you want to continue? (yes/no) [yes]:
 > 


In SiteInstallCommands.php line 181:
                                                                                               
  Existing configuration directory not found or does not contain a core.extension.yml file.".  
                                                                                               

Failed to run drush si --existing-config: exit status 1
```

**Comment by edysmp** [comment]
Make sure to add settings for the config sync directory within the `settings.php` file.

You'll need to track the settings.php file into git. Make this expection in the .gitignore https://github.com/edysmp/casa-luis/blob/main/.gitignore#L18

**Comment by Luis93Hub** [comment]
"Add_Config"

**Comment by edysmp** [comment]
the "vendor", "web/core" and other files in "web/"  folders should not be added. Make sure you are adding the config folder only and that the site can be installed with `drush ddev site:install --existing-config` command.

**Review by edysmp — APPROVED** [review]

**Comment by edysmp** [comment]
@Luis93Hub Good job! Changes looks good.

**Pull request merged**
